<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class BacSiSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('bac_sis')->truncate();

        DB::table('bac_sis')->insert([
            [
                'id' => 1,
                'ho_ten' => 'BS. Trần Anh A',
                'email' => 'trananha@petcare.vn',
                'password' => bcrypt('123456'),
                'so_dien_thoai' => '0912345601',
                'ngay_sinh' => '1985-03-15',
                'gioi_tinh' => 1,
                'mo_ta' => 'Bác sĩ thú y chuyên khám tổng quát cho chó, mèo và thú cưng.',
                'hinh_anh' => 'https://i.pravatar.cc/300?img=11',
                'chuc_danh' => 'Bác sĩ thú y',
                'so_nam_kinh_nghiem' => '12',
                'kinh_nghiem_lam_viec' => 'PetCare Đà Nẵng',
                'qua_trinh_dao_tao' => 'Học viện Nông nghiệp Việt Nam',
                'chung_chi' => 'Chứng chỉ hành nghề Thú y',
                'thanh_tuu' => 'Hơn 5.000 ca khám và điều trị thú cưng thành công',
                'thanh_vien_to_chuc' => 'Hội Thú y Việt Nam',
                'tinh_trang' => 1,
                'id_phong_kham' => 1,
                'is_active' => 1,
                'is_block' => 0,
                'hash_reset' => null,
                'hash_active' => null,
                'don_gia_kham' => 150000,
            ],
            [
                'id' => 2,
                'ho_ten' => 'BS. Trần Anh B',
                'email' => 'trananhb@petcare.vn',
                'password' => bcrypt('123456'),
                'so_dien_thoai' => '0912345602',
                'ngay_sinh' => '1988-07-20',
                'gioi_tinh' => 0,
                'mo_ta' => 'Bác sĩ thú y chuyên nội khoa và bệnh truyền nhiễm.',
                'hinh_anh' => 'https://i.pravatar.cc/300?img=32',
                'chuc_danh' => 'Bác sĩ thú y',
                'so_nam_kinh_nghiem' => '10',
                'kinh_nghiem_lam_viec' => 'PetCare Hà Nội',
                'qua_trinh_dao_tao' => 'Đại học Nông Lâm TP.HCM',
                'chung_chi' => 'Chứng chỉ Nội khoa Thú y',
                'thanh_tuu' => 'Điều trị thành công nhiều ca Parvo và Care',
                'thanh_vien_to_chuc' => 'Hội Thú y Việt Nam',
                'tinh_trang' => 1,
                'id_phong_kham' => 2,
                'is_active' => 1,
                'is_block' => 0,
                'hash_reset' => null,
                'hash_active' => null,
                'don_gia_kham' => 180000,
            ],
            [
                'id' => 3,
                'ho_ten' => 'BS. Trần Anh C',
                'email' => 'trananhc@petcare.vn',
                'password' => bcrypt('123456'),
                'so_dien_thoai' => '0912345603',
                'ngay_sinh' => '1984-09-12',
                'gioi_tinh' => 1,
                'mo_ta' => 'Bác sĩ thú y chuyên ngoại khoa và phẫu thuật.',
                'hinh_anh' => 'https://i.pravatar.cc/300?img=15',
                'chuc_danh' => 'Bác sĩ thú y',
                'so_nam_kinh_nghiem' => '14',
                'kinh_nghiem_lam_viec' => 'PetCare Hồ Chí Minh',
                'qua_trinh_dao_tao' => 'Đại học Cần Thơ',
                'chung_chi' => 'Chứng chỉ Phẫu thuật Thú y',
                'thanh_tuu' => 'Hơn 2.000 ca phẫu thuật thành công',
                'thanh_vien_to_chuc' => 'Hội Bác sĩ Thú y Việt Nam',
                'tinh_trang' => 1,
                'id_phong_kham' => 3,
                'is_active' => 1,
                'is_block' => 0,
                'hash_reset' => null,
                'hash_active' => null,
                'don_gia_kham' => 250000,
            ],
            [
                'id' => 4,
                'ho_ten' => 'BS. Trần Anh D',
                'email' => 'trananhd@petcare.vn',
                'password' => bcrypt('123456'),
                'so_dien_thoai' => '0912345604',
                'ngay_sinh' => '1990-01-25',
                'gioi_tinh' => 0,
                'mo_ta' => 'Bác sĩ thú y chuyên da liễu và ký sinh trùng.',
                'hinh_anh' => 'https://i.pravatar.cc/300?img=45',
                'chuc_danh' => 'Bác sĩ thú y',
                'so_nam_kinh_nghiem' => '8',
                'kinh_nghiem_lam_viec' => 'PetCare Đà Nẵng',
                'qua_trinh_dao_tao' => 'Học viện Nông nghiệp Việt Nam',
                'chung_chi' => 'Chứng chỉ Da liễu Thú y',
                'thanh_tuu' => 'Điều trị hơn 3.000 ca bệnh ngoài da',
                'thanh_vien_to_chuc' => 'Hội Thú y Việt Nam',
                'tinh_trang' => 1,
                'id_phong_kham' => 4,
                'is_active' => 1,
                'is_block' => 0,
                'hash_reset' => null,
                'hash_active' => null,
                'don_gia_kham' => 170000,
            ],
            [
                'id' => 5,
                'ho_ten' => 'BS. Trần Anh E',
                'email' => 'trananhe@petcare.vn',
                'password' => bcrypt('123456'),
                'so_dien_thoai' => '0912345605',
                'ngay_sinh' => '1987-06-18',
                'gioi_tinh' => 1,
                'mo_ta' => 'Bác sĩ thú y chuyên tiêm phòng và chăm sóc sức khỏe định kỳ.',
                'hinh_anh' => 'https://i.pravatar.cc/300?img=18',
                'chuc_danh' => 'Bác sĩ thú y',
                'so_nam_kinh_nghiem' => '11',
                'kinh_nghiem_lam_viec' => 'PetCare Hải Phòng',
                'qua_trinh_dao_tao' => 'Đại học Nông Lâm Huế',
                'chung_chi' => 'Chứng chỉ Tiêm phòng Thú y',
                'thanh_tuu' => 'Thực hiện hơn 10.000 mũi tiêm phòng',
                'thanh_vien_to_chuc' => 'Hội Thú y Việt Nam',
                'tinh_trang' => 1,
                'id_phong_kham' => 5,
                'is_active' => 1,
                'is_block' => 0,
                'hash_reset' => null,
                'hash_active' => null,
                'don_gia_kham' => 120000,
            ],
            [
                'id' => 6,
                'ho_ten' => 'BS. Trần Anh F',
                'email' => 'trananhf@petcare.vn',
                'password' => bcrypt('123456'),
                'so_dien_thoai' => '0912345606',
                'ngay_sinh' => '1988-04-12',
                'gioi_tinh' => 1,
                'mo_ta' => 'Bác sĩ thú y chuyên ngoại khoa và phẫu thuật thú cưng.',
                'hinh_anh' => 'https://i.pravatar.cc/300?img=21',
                'chuc_danh' => 'Bác sĩ thú y',
                'so_nam_kinh_nghiem' => '9',
                'kinh_nghiem_lam_viec' => 'PetCare Đà Nẵng',
                'qua_trinh_dao_tao' => 'Đại học Nông Lâm TP.HCM',
                'chung_chi' => 'Chứng chỉ Phẫu thuật Thú y',
                'thanh_tuu' => 'Thực hiện hơn 2.500 ca phẫu thuật thành công',
                'thanh_vien_to_chuc' => 'Hội Thú y Việt Nam',
                'tinh_trang' => 1,
                'id_phong_kham' => 1,
                'is_active' => 1,
                'is_block' => 0,
                'hash_reset' => null,
                'hash_active' => null,
                'don_gia_kham' => 250000,
            ],
            [
                'id' => 7,
                'ho_ten' => 'BS. Trần Anh G',
                'email' => 'trananhg@petcare.vn',
                'password' => bcrypt('123456'),
                'so_dien_thoai' => '0912345607',
                'ngay_sinh' => '1986-09-10',
                'gioi_tinh' => 1,
                'mo_ta' => 'Bác sĩ thú y chuyên chẩn đoán hình ảnh và siêu âm.',
                'hinh_anh' => 'https://i.pravatar.cc/300?img=22',
                'chuc_danh' => 'Bác sĩ thú y',
                'so_nam_kinh_nghiem' => '13',
                'kinh_nghiem_lam_viec' => 'PetCare Cần Thơ',
                'qua_trinh_dao_tao' => 'Học viện Nông nghiệp Việt Nam',
                'chung_chi' => 'Chứng chỉ Chẩn đoán hình ảnh',
                'thanh_tuu' => 'Hơn 8.000 ca siêu âm thú cưng',
                'thanh_vien_to_chuc' => 'Hội Thú y Việt Nam',
                'tinh_trang' => 1,
                'id_phong_kham' => 2,
                'is_active' => 1,
                'is_block' => 0,
                'hash_reset' => null,
                'hash_active' => null,
                'don_gia_kham' => 180000,
            ],
            [
                'id' => 8,
                'ho_ten' => 'BS. Trần Anh H',
                'email' => 'trananhh@petcare.vn',
                'password' => bcrypt('123456'),
                'so_dien_thoai' => '0912345608',
                'ngay_sinh' => '1990-02-08',
                'gioi_tinh' => 0,
                'mo_ta' => 'Bác sĩ thú y chuyên sản khoa và chăm sóc thú sơ sinh.',
                'hinh_anh' => 'https://i.pravatar.cc/300?img=47',
                'chuc_danh' => 'Bác sĩ thú y',
                'so_nam_kinh_nghiem' => '8',
                'kinh_nghiem_lam_viec' => 'PetCare Hà Nội',
                'qua_trinh_dao_tao' => 'Đại học Cần Thơ',
                'chung_chi' => 'Chứng chỉ Sản khoa Thú y',
                'thanh_tuu' => 'Đỡ sinh thành công hơn 1.200 ca',
                'thanh_vien_to_chuc' => 'Hội Thú y Việt Nam',
                'tinh_trang' => 1,
                'id_phong_kham' => 3,
                'is_active' => 1,
                'is_block' => 0,
                'hash_reset' => null,
                'hash_active' => null,
                'don_gia_kham' => 200000,
            ],
            [
                'id' => 9,
                'ho_ten' => 'BS. Trần Anh I',
                'email' => 'trananhi@petcare.vn',
                'password' => bcrypt('123456'),
                'so_dien_thoai' => '0912345609',
                'ngay_sinh' => '1984-11-20',
                'gioi_tinh' => 1,
                'mo_ta' => 'Bác sĩ thú y chuyên tim mạch và hô hấp.',
                'hinh_anh' => 'https://i.pravatar.cc/300?img=24',
                'chuc_danh' => 'Bác sĩ thú y',
                'so_nam_kinh_nghiem' => '15',
                'kinh_nghiem_lam_viec' => 'PetCare TP.HCM',
                'qua_trinh_dao_tao' => 'Đại học Nông Lâm Huế',
                'chung_chi' => 'Chứng chỉ Tim mạch Thú y',
                'thanh_tuu' => 'Điều trị thành công nhiều ca suy tim ở chó mèo',
                'thanh_vien_to_chuc' => 'Hội Thú y Việt Nam',
                'tinh_trang' => 1,
                'id_phong_kham' => 4,
                'is_active' => 1,
                'is_block' => 0,
                'hash_reset' => null,
                'hash_active' => null,
                'don_gia_kham' => 220000,
            ],
            [
                'id' => 10,
                'ho_ten' => 'BS. Trần Anh K',
                'email' => 'trananhk@petcare.vn',
                'password' => bcrypt('123456'),
                'so_dien_thoai' => '0912345610',
                'ngay_sinh' => '1989-08-05',
                'gioi_tinh' => 1,
                'mo_ta' => 'Bác sĩ thú y chuyên điều trị ký sinh trùng.',
                'hinh_anh' => 'https://i.pravatar.cc/300?img=25',
                'chuc_danh' => 'Bác sĩ thú y',
                'so_nam_kinh_nghiem' => '10',
                'kinh_nghiem_lam_viec' => 'PetCare Hải Phòng',
                'qua_trinh_dao_tao' => 'Đại học Nông Lâm TP.HCM',
                'chung_chi' => 'Chứng chỉ Ký sinh trùng',
                'thanh_tuu' => 'Hơn 6.000 ca điều trị thành công',
                'thanh_vien_to_chuc' => 'Hội Thú y Việt Nam',
                'tinh_trang' => 1,
                'id_phong_kham' => 5,
                'is_active' => 1,
                'is_block' => 0,
                'hash_reset' => null,
                'hash_active' => null,
                'don_gia_kham' => 160000,
            ],
            [
                'id' => 11,
                'ho_ten' => 'BS. Trần Anh L',
                'email' => 'trananhl@petcare.vn',
                'password' => bcrypt('123456'),
                'so_dien_thoai' => '0912345611',
                'ngay_sinh' => '1987-12-01',
                'gioi_tinh' => 0,
                'mo_ta' => 'Bác sĩ thú y chuyên nha khoa thú cưng.',
                'hinh_anh' => 'https://i.pravatar.cc/300?img=48',
                'chuc_danh' => 'Bác sĩ thú y',
                'so_nam_kinh_nghiem' => '11',
                'kinh_nghiem_lam_viec' => 'PetCare Huế',
                'qua_trinh_dao_tao' => 'Học viện Nông nghiệp Việt Nam',
                'chung_chi' => 'Chứng chỉ Nha khoa Thú y',
                'thanh_tuu' => 'Hơn 4.000 ca điều trị răng miệng',
                'thanh_vien_to_chuc' => 'Hội Thú y Việt Nam',
                'tinh_trang' => 1,
                'id_phong_kham' => 1,
                'is_active' => 1,
                'is_block' => 0,
                'hash_reset' => null,
                'hash_active' => null,
                'don_gia_kham' => 170000,
            ],
            [
                'id' => 12,
                'ho_ten' => 'BS. Trần Anh M',
                'email' => 'trananhm@petcare.vn',
                'password' => bcrypt('123456'),
                'so_dien_thoai' => '0912345612',
                'ngay_sinh' => '1985-10-15',
                'gioi_tinh' => 1,
                'mo_ta' => 'Bác sĩ thú y chuyên dinh dưỡng và chăm sóc thú cưng.',
                'hinh_anh' => 'https://i.pravatar.cc/300?img=27',
                'chuc_danh' => 'Bác sĩ thú y',
                'so_nam_kinh_nghiem' => '12',
                'kinh_nghiem_lam_viec' => 'PetCare Nha Trang',
                'qua_trinh_dao_tao' => 'Đại học Cần Thơ',
                'chung_chi' => 'Chứng chỉ Dinh dưỡng Thú y',
                'thanh_tuu' => 'Xây dựng chế độ ăn cho hơn 3.000 thú cưng',
                'thanh_vien_to_chuc' => 'Hội Thú y Việt Nam',
                'tinh_trang' => 1,
                'id_phong_kham' => 2,
                'is_active' => 1,
                'is_block' => 0,
                'hash_reset' => null,
                'hash_active' => null,
                'don_gia_kham' => 180000,
            ],
            [
                'id' => 13,
                'ho_ten' => 'BS. Trần Anh N',
                'email' => 'trananhn@petcare.vn',
                'password' => bcrypt('123456'),
                'so_dien_thoai' => '0912345613',
                'ngay_sinh' => '1983-05-18',
                'gioi_tinh' => 1,
                'mo_ta' => 'Bác sĩ thú y chuyên cấp cứu và hồi sức.',
                'hinh_anh' => 'https://i.pravatar.cc/300?img=28',
                'chuc_danh' => 'Bác sĩ thú y',
                'so_nam_kinh_nghiem' => '16',
                'kinh_nghiem_lam_viec' => 'PetCare Bình Dương',
                'qua_trinh_dao_tao' => 'Đại học Nông Lâm TP.HCM',
                'chung_chi' => 'Chứng chỉ Cấp cứu Thú y',
                'thanh_tuu' => 'Cứu sống hàng nghìn ca nguy kịch',
                'thanh_vien_to_chuc' => 'Hội Thú y Việt Nam',
                'tinh_trang' => 1,
                'id_phong_kham' => 3,
                'is_active' => 1,
                'is_block' => 0,
                'hash_reset' => null,
                'hash_active' => null,
                'don_gia_kham' => 300000,
            ],
            [
                'id' => 14,
                'ho_ten' => 'BS. Trần Anh P',
                'email' => 'trananhp@petcare.vn',
                'password' => bcrypt('123456'),
                'so_dien_thoai' => '0912345614',
                'ngay_sinh' => '1986-06-09',
                'gioi_tinh' => 0,
                'mo_ta' => 'Bác sĩ thú y chuyên xét nghiệm và chẩn đoán bệnh.',
                'hinh_anh' => 'https://i.pravatar.cc/300?img=49',
                'chuc_danh' => 'Bác sĩ thú y',
                'so_nam_kinh_nghiem' => '10',
                'kinh_nghiem_lam_viec' => 'PetCare Vũng Tàu',
                'qua_trinh_dao_tao' => 'Học viện Nông nghiệp Việt Nam',
                'chung_chi' => 'Chứng chỉ Xét nghiệm Thú y',
                'thanh_tuu' => 'Hơn 15.000 mẫu xét nghiệm',
                'thanh_vien_to_chuc' => 'Hội Thú y Việt Nam',
                'tinh_trang' => 1,
                'id_phong_kham' => 4,
                'is_active' => 1,
                'is_block' => 0,
                'hash_reset' => null,
                'hash_active' => null,
                'don_gia_kham' => 180000,
            ],
            [
                'id' => 15,
                'ho_ten' => 'BS. Trần Anh Q',
                'email' => 'trananhq@petcare.vn',
                'password' => bcrypt('123456'),
                'so_dien_thoai' => '0912345615',
                'ngay_sinh' => '1984-01-30',
                'gioi_tinh' => 1,
                'mo_ta' => 'Bác sĩ thú y chuyên chăm sóc và phục hồi chức năng cho thú cưng.',
                'hinh_anh' => 'https://i.pravatar.cc/300?img=30',
                'chuc_danh' => 'Bác sĩ thú y',
                'so_nam_kinh_nghiem' => '14',
                'kinh_nghiem_lam_viec' => 'PetCare TP.HCM',
                'qua_trinh_dao_tao' => 'Đại học Nông Lâm Huế',
                'chung_chi' => 'Chứng chỉ Phục hồi chức năng Thú y',
                'thanh_tuu' => 'Điều trị thành công nhiều ca chấn thương',
                'thanh_vien_to_chuc' => 'Hội Thú y Việt Nam',
                'tinh_trang' => 1,
                'id_phong_kham' => 5,
                'is_active' => 1,
                'is_block' => 0,
                'hash_reset' => null,
                'hash_active' => null,
                'don_gia_kham' => 220000,
            ],
        ]);
    }
}
