<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class LeTanSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('le_tans')->truncate();

        DB::table('le_tans')->insert([
            [
                'ho_ten'         => 'Nguyễn Thị Lan',
                'email'          => 'lan@gmail.com',
                'password'       => bcrypt('123456'),
                'hinh_anh'       => 'https://i.pravatar.cc/300?img=1',
                'so_dien_thoai'  => '0901000001',
                'ngay_sinh'      => '1998-01-15',
                'gioi_tinh'      => 1,
                'dia_chi'        => 'Đà Nẵng',
                'ma_le_tan'      => 'LT001',
                'ngay_vao_lam'   => '2024-01-10',
                'hash_reset'     => null,
                'hash_active'    => null,
                'is_active'      => 1,
                'is_block'       => 0,
                'tinh_trang'     => 1,
                'created_at'     => now(),
                'updated_at'     => now(),
            ],
            [
                'ho_ten'         => 'Trần Văn Minh',
                'email'          => 'minh@gmail.com',
                'password'       => bcrypt('123456'),
                'hinh_anh'       => 'https://i.pravatar.cc/300?img=2',
                'so_dien_thoai'  => '0901000002',
                'ngay_sinh'      => '1995-05-10',
                'gioi_tinh'      => 0,
                'dia_chi'        => 'Huế',
                'ma_le_tan'      => 'LT002',
                'ngay_vao_lam'   => '2024-02-01',
                'hash_reset'     => null,
                'hash_active'    => null,
                'is_active'      => 1,
                'is_block'       => 0,
                'tinh_trang'     => 1,
                'created_at'     => now(),
                'updated_at'     => now(),
            ],
            [
                'ho_ten'         => 'Lê Thị Mai',
                'email'          => 'mai@gmail.com',
                'password'       => bcrypt('123456'),
                'hinh_anh'       => 'https://i.pravatar.cc/300?img=3',
                'so_dien_thoai'  => '0901000003',
                'ngay_sinh'      => '1999-08-20',
                'gioi_tinh'      => 1,
                'dia_chi'        => 'Quảng Nam',
                'ma_le_tan'      => 'LT003',
                'ngay_vao_lam'   => '2024-03-15',
                'hash_reset'     => null,
                'hash_active'    => null,
                'is_active'      => 1,
                'is_block'       => 0,
                'tinh_trang'     => 1,
                'created_at'     => now(),
                'updated_at'     => now(),
            ],
            [
                'ho_ten'         => 'Phạm Quốc Huy',
                'email'          => 'huy@gmail.com',
                'password'       => bcrypt('123456'),
                'hinh_anh'       => 'https://i.pravatar.cc/300?img=4',
                'so_dien_thoai'  => '0901000004',
                'ngay_sinh'      => '1997-03-12',
                'gioi_tinh'      => 0,
                'dia_chi'        => 'Quảng Ngãi',
                'ma_le_tan'      => 'LT004',
                'ngay_vao_lam'   => '2024-01-20',
                'hash_reset'     => null,
                'hash_active'    => null,
                'is_active'      => 1,
                'is_block'       => 0,
                'tinh_trang'     => 1,
                'created_at'     => now(),
                'updated_at'     => now(),
            ],
            [
                'ho_ten'         => 'Đỗ Thị Hương',
                'email'          => 'huong@gmail.com',
                'password'       => bcrypt('123456'),
                'hinh_anh'       => 'https://i.pravatar.cc/300?img=5',
                'so_dien_thoai'  => '0901000005',
                'ngay_sinh'      => '1996-07-18',
                'gioi_tinh'      => 1,
                'dia_chi'        => 'Đà Nẵng',
                'ma_le_tan'      => 'LT005',
                'ngay_vao_lam'   => '2024-04-01',
                'hash_reset'     => null,
                'hash_active'    => null,
                'is_active'      => 1,
                'is_block'       => 0,
                'tinh_trang'     => 1,
                'created_at'     => now(),
                'updated_at'     => now(),
            ],
            [
                'ho_ten'         => 'Võ Minh Khoa',
                'email'          => 'khoa@gmail.com',
                'password'       => bcrypt('123456'),
                'hinh_anh'       => 'https://i.pravatar.cc/300?img=6',
                'so_dien_thoai'  => '0901000006',
                'ngay_sinh'      => '1994-09-11',
                'gioi_tinh'      => 0,
                'dia_chi'        => 'Huế',
                'ma_le_tan'      => 'LT006',
                'ngay_vao_lam'   => '2024-02-18',
                'hash_reset'     => null,
                'hash_active'    => null,
                'is_active'      => 1,
                'is_block'       => 0,
                'tinh_trang'     => 1,
                'created_at'     => now(),
                'updated_at'     => now(),
            ],
            [
                'ho_ten'         => 'Ngô Thị Ngọc',
                'email'          => 'ngoc@gmail.com',
                'password'       => bcrypt('123456'),
                'hinh_anh'       => 'https://i.pravatar.cc/300?img=7',
                'so_dien_thoai'  => '0901000007',
                'ngay_sinh'      => '1998-10-05',
                'gioi_tinh'      => 1,
                'dia_chi'        => 'Tam Kỳ',
                'ma_le_tan'      => 'LT007',
                'ngay_vao_lam'   => '2024-05-10',
                'hash_reset'     => null,
                'hash_active'    => null,
                'is_active'      => 1,
                'is_block'       => 0,
                'tinh_trang'     => 1,
                'created_at'     => now(),
                'updated_at'     => now(),
            ],
            [
                'ho_ten'         => 'Hoàng Đức Anh',
                'email'          => 'anh@gmail.com',
                'password'       => bcrypt('123456'),
                'hinh_anh'       => 'https://i.pravatar.cc/300?img=8',
                'so_dien_thoai'  => '0901000008',
                'ngay_sinh'      => '1993-11-08',
                'gioi_tinh'      => 0,
                'dia_chi'        => 'Hội An',
                'ma_le_tan'      => 'LT008',
                'ngay_vao_lam'   => '2024-06-05',
                'hash_reset'     => null,
                'hash_active'    => null,
                'is_active'      => 1,
                'is_block'       => 0,
                'tinh_trang'     => 1,
                'created_at'     => now(),
                'updated_at'     => now(),
            ],
            [
                'ho_ten'         => 'Bùi Thị Hạnh',
                'email'          => 'hanh@gmail.com',
                'password'       => bcrypt('123456'),
                'hinh_anh'       => 'https://i.pravatar.cc/300?img=9',
                'so_dien_thoai'  => '0901000009',
                'ngay_sinh'      => '1997-04-25',
                'gioi_tinh'      => 1,
                'dia_chi'        => 'Đà Nẵng',
                'ma_le_tan'      => 'LT009',
                'ngay_vao_lam'   => '2024-03-20',
                'hash_reset'     => null,
                'hash_active'    => null,
                'is_active'      => 1,
                'is_block'       => 0,
                'tinh_trang'     => 1,
                'created_at'     => now(),
                'updated_at'     => now(),
            ],
            [
                'ho_ten'         => 'Phan Quốc Bảo',
                'email'          => 'bao@gmail.com',
                'password'       => bcrypt('123456'),
                'hinh_anh'       => 'https://i.pravatar.cc/300?img=10',
                'so_dien_thoai'  => '0901000010',
                'ngay_sinh'      => '1996-12-30',
                'gioi_tinh'      => 0,
                'dia_chi'        => 'Quảng Nam',
                'ma_le_tan'      => 'LT010',
                'ngay_vao_lam'   => '2024-07-01',
                'hash_reset'     => null,
                'hash_active'    => null,
                'is_active'      => 1,
                'is_block'       => 0,
                'tinh_trang'     => 1,
                'created_at'     => now(),
                'updated_at'     => now(),
            ],
        ]);

    }
}
